### ISSUE TITLE
taxonomy/terms 경로 

### ISSUE THREAD

**Issue by suncrud** [team-durumi/tailwind-aa-theme#1]
확인해보니 taxonomy / term 템플릿이 

- layouts/_default/
- layouts/tags/ 

요렇게 두 군데 있는데 둘다 필요한지 궁금합니당.

**Comment by woonjjang** [comment]
하나를 지워 보시고 테스트 해 보시면 이해할 수 있는데

layouts/_default/ -> tags/venues/creators 등등 생성한 taxonomy & term 모두에 반영되는 페이지입니다. 
layouts/tags/ -> 태그 화면에만 별도 화면을 적용할 때 

모두를 동일하게 맞출거면 통일해도 됩니다.
레이아웃 구분하는 것을 설명하려고 남겨놨었습니다. ㅎ

**Comment by mozodev** [comment]
쉽지는 않겠지만 읽고 나름 머리속에 그림을 그려야...
https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-taxonomy-pages
대강의 개념은 보다 구체적인 템플릿을 찾다가 없으면 fallback으로 _default...

**Comment by suncrud** [comment]
ㅎㅎ 네네 둘 다 따로 있을 필요가 있나 해서 한번 여쭈어봤습니다.

**Comment by suncrud** [comment]
둘다 템플릿을 확인해봤는데, 

- term.html 파일은 서로 거의 비슷하고 
- taxonomy.html 템플릿은 tags/ 디렉토리 밑에 있는 파일이 이미지카드 형식을 취하고 있는데 ( [참조 - CCWPS](https://ccwps.org/venues/dmz/)) 추상화되어있어야 할 테마로서 이미지가 없는 태그결과에 대한 대응이 미비하다고 생각해서 삭제함. 이미지리스트 필요한 경우에는 각 프로젝트에 위에 링크 건 ccwps 페이지 이미지카드 쓸 수 있다고 판단

그래서 layouts/tags/ 디렉토리 삭제했음.

일단 닫을테니 이슈 있으면 다시 열어주세요.
